FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@9.12.0 --activate
RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY prisma/package.json prisma/package.json
RUN pnpm install --frozen-lockfile --filter @tongqian/prisma...

COPY prisma prisma

CMD ["pnpm", "--dir", "prisma", "prisma", "migrate", "deploy"]
