import { AiDisclaimer, PageContent, PageHeader, PageLayout, SectionCard } from '@tongqian/ui';

export default function SharePage({ params }: { params: { token: string } }): JSX.Element {
  return (
    <PageLayout className="bg-stitch-surface text-stitch-on-surface">
      <PageContent>
        <PageHeader breadcrumbs="Shared link" description="Generated by Tongqian construction AI business steward." title="Shared AI result" />
        <SectionCard title={`Token ${params.token}`}>
          <p className="text-sm text-stitch-on-surface-variant">This share link defaults to 24h expiry and read-count control.</p>
        </SectionCard>
        <AiDisclaimer variant="footer" />
      </PageContent>
    </PageLayout>
  );
}
